[project]
name = "k8s-react-ai"
version = "0.1.0"
description = "A ReAct AI to analyze Kubernetes clusters."
requires-python = ">=3.11"
dependencies = [
    "pydantic",
    "openai",
    "python-dotenv",
    "pydantic-ai",
]

[tool.uv]
dev-dependencies = [
    "pytest",
] 